import { useState } from 'react';
import { ActionButton, BuildingArt, canAfford, capacitySummary, formatDuration, quoteText, resourceLabels } from './ui.jsx';

function Plot({ slot, index, state, selected, onSelect }) { const job = state.city.constructionQueue.find(item => item.slotId === slot.id); return <button type="button" className={`plot ${slot.building ?? 'empty'}${selected ? ' selected' : ''}${job ? ' building' : ''}`} aria-pressed={selected} aria-label={slot.building ? `${state.buildings[slot.building].label}, Stufe ${slot.level}, Grundstück ${index + 1}` : `Freies Grundstück ${index + 1}`} onClick={onSelect}><span className="plot-number">{index + 1}</span>{slot.building ? <><BuildingArt type={slot.building}/><strong>{state.buildings[slot.building].label}</strong><small>Stufe {slot.level}</small></> : <><span className="empty-mark">+</span><strong>Freies Grundstück</strong></>}{job && <span className="queued-badge">{job === state.city.constructionQueue[0] ? 'Baustelle' : 'Eingeplant'}</span>}</button>; }

export function CityView({ state, transport, onPreview }) {
  const [selectedId, setSelectedId] = useState(null); const slot = state.city.buildingSlots.find(item => item.id === selectedId); const busy = transport.hasPending();
  const construct = (slotId, building) => { try { transport.mutate('construction.enqueue', { slotId, building }); } catch (error) { transport.setMessage(error.message); } };
  return <div className="game-layout"><section className="map-panel" aria-labelledby="city-heading"><div className="heading"><div><span className="kicker">STADTANSICHT</span><h2 id="city-heading">Siedlung</h2></div><span>Grundstück auswählen</span></div><div className="city-scene"><div className="river"/><div className="road horizontal"/><div className="road vertical"/><div className="city-grid" aria-label="Bauplätze">{state.city.buildingSlots.map((item, index) => <Plot key={item.id} slot={item} index={index} state={state} selected={item.id === selectedId} onSelect={() => setSelectedId(item.id)}/>)}</div></div></section><aside><section className="card selection" aria-live="polite"><Selection slot={slot} state={state} busy={busy} construct={construct} onPreview={onPreview}/></section><ConstructionQueue state={state}/></aside></div>;
}
function Selection({ slot, state, busy, construct, onPreview }) {
  if (!slot) return <p>Wähle ein Grundstück in der Stadt, um zu bauen oder auszubauen.</p>;
  const queued = state.city.constructionQueue.some(job => job.slotId === slot.id); const definition = slot.building && state.buildings[slot.building]; const quote = state.offers.upgrade[slot.id];
  return <><span className="kicker">GRUNDSTÜCK {slot.id.split('-')[1]}</span><h2>{definition?.label ?? 'Freies Grundstück'}</h2>{queued ? <p className="notice">Für dieses Grundstück ist bereits ein Auftrag eingeplant.</p> : slot.building ? <>{<p>{definition.resource ? `Stufe ${slot.level} · ${slot.level} ${resourceLabels[definition.resource]} pro Sekunde` : `Stufe ${slot.level} · erhöht alle Lagerkapazitäten`}</p>}{quote ? <ActionButton label={`Auf Stufe ${quote.level} ausbauen`} detail={`${quoteText(quote)} · Lager danach: ${capacitySummary(quote.capacityAfter)}`} disabled={busy || !canAfford(state, quote)} onClick={() => construct(slot.id, slot.building)}/> : <p className="notice">Maximale Stufe erreicht.</p>}<ActionButton label="Gebäude abreißen" detail="Vorschau mit Rückerstattung und Folgen öffnen" disabled={busy} onClick={() => onPreview(slot)}/></> : <><p>Errichte ein Produktions- oder Lagergebäude.</p><div className="actions">{Object.entries(state.buildings).filter(([, item]) => item.area === 'civil').map(([key, item]) => <ActionButton key={key} label={item.label} detail={quoteText(state.offers.build[key])} disabled={busy || !canAfford(state, state.offers.build[key])} onClick={() => construct(slot.id, key)}/>)}</div></>}</>;
}
function ConstructionQueue({ state }) { return <section className="card queue" aria-labelledby="queue-heading"><div className="queue-title"><h2 id="queue-heading">Bauplan</h2><span>{state.city.constructionQueue.length} / {state.maxQueueLength}</span></div><ol>{state.city.constructionQueue.length ? state.city.constructionQueue.map((job, index) => <li key={job.id}><span className="queue-position">{index + 1}</span><strong>{state.buildings[job.building].label} · Stufe {job.level}</strong><span>{index ? 'wartet' : `noch ${formatDuration(job.finishesAt - state.serverTime)}`}</span></li>) : <li className="empty-queue">Keine Bauaufträge.</li>}</ol></section>; }
